# -----------------------------
# HEADLESS SERVICE (StatefulSet)
# -----------------------------
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx
spec:
  clusterIP: None
  selector:
    app: nginx
  ports:
  - port: 80
    name: web
---
# -----------------------------
# NORMAL CLUSTERIP SERVICE
# -----------------------------
apiVersion: v1
kind: Service
metadata:
  name: nginx-normal
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: web
---
# -----------------------------
# STATEFULSET
# -----------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: nginx-headless
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # -----------------------------
      # INIT CONTAINER
      # -----------------------------
      initContainers:
      - name: init-html
        image: busybox:1.36
        command:
        - sh
        - -c
        - |
          echo "Hello from StatefulSet pod $HOSTNAME" > /workdir/index.html
        volumeMounts:
        - name: shared-volume
          mountPath: /workdir

      # -----------------------------
      # MAIN CONTAINER
      # -----------------------------
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: shared-volume
          mountPath: /usr/share/nginx/html
        - name: www
          mountPath: /usr/share/nginx

      # -----------------------------
      # EMPTYDIR (SHARED WITH INIT)
      # -----------------------------
      volumes:
      - name: shared-volume
        emptyDir: {}

  # -----------------------------
  # PER-POD PERSISTENT VOLUME
  # -----------------------------
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi
